apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    nfs: postgres
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /rootfs_homeassistant-postgres/
    server: 192.168.1.142
