apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    nfs: postgres
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - nfsvers=3
  nfs:
    path: /media/pi/Elements/k8sNFS/postgres/
    server: 192.168.1.91